Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 0
Gtk/DecorationLayout "icon:minimize,maximize,close"
Net/ThemeName "Gruvbox-B-LB-Dark-Medium"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gtk/CursorThemeSize 24
Gtk/CursorThemeName "GoogleDot-Black"
Net/SoundThemeName "ocean"
Net/IconThemeName "Gruvbox-Plus-Dark"
Gtk/FontName "CaskaydiaCove Nerd Font, Bold 16"

