set -g status-bg "#16161D"
set -g status-fg "#DCD7BA"
set -g status-left "#[fg=#16161D,bg=#E6C384,bold] #S #[fg=#16161D,bg=#16161D]"
set -g window-status-format "#[fg=#938056,bg=#16161D] #I:#W "
set -g window-status-current-format "#[fg=#16161D,bg=#8094B4,bold] #I:#W #[fg=#16161D,bg=#16161D]"
set -g window-status-activity-style "fg=#FFA066,bg=#16161D"
set -g window-status-bell-style "fg=#E82424,bg=#16161D,bold"
set -g status-right "#[fg=#2A2A37,bg=#16161D]#[fg=#DCD7BA,bg=#2A2A37] %H:%M  %d/%m #[fg=#E6C384,bg=#2A2A37]#[fg=#16161D,bg=#E6C384,bold] #h "
set -g pane-border-style "fg=#2A2A37"
set -g pane-active-border-style "fg=#E6C384"
set -g message-style "fg=#E6C384,bg=#363646"
set -g message-command-style "fg=#FFA066,bg=#363646"
set -g mode-style "fg=#16161D,bg=#E6C384,bold"
set -g clock-mode-colour "#E6C384"
set -g popup-style "fg=#DCD7BA,bg=#2A2A37"
set -g popup-border-style "fg=#54546D,bg=#2A2A37"
