vim.pack.add({
	-- shared/no config deps
	"https://github.com/nvim-lua/plenary.nvim",
	"https://github.com/christoomey/vim-tmux-navigator",
	"https://github.com/hrsh7th/cmp-buffer",
	"https://github.com/hrsh7th/cmp-path",
	"https://github.com/hrsh7th/cmp-nvim-lsp",
	"https://github.com/folke/todo-comments.nvim",
	"https://github.com/aznhe21/actions-preview.nvim",
	"https://github.com/L3MON4D3/LuaSnip",
	"https://github.com/MunifTanjim/nui.nvim",
	"https://github.com/folke/which-key.nvim",
	"https://github.com/rafamadriz/friendly-snippets",
	"https://github.com/saadparwaiz1/cmp_luasnip",
	"https://github.com/lewis6991/gitsigns.nvim",
	"https://github.com/catgoose/nvim-colorizer.lua",
	"https://github.com/nvim-tree/nvim-web-devicons",
	"https://github.com/mason-org/mason-lspconfig.nvim",
	"https://github.com/onsails/lspkind.nvim",

	-- ui
	"https://github.com/rebelot/kanagawa.nvim",
	"https://github.com/nvim-lualine/lualine.nvim",
	"https://github.com/lukas-reineke/indent-blankline.nvim",
	"https://github.com/echasnovski/mini.indentscope",
	"https://github.com/karb94/neoscroll.nvim",
	"https://github.com/folke/noice.nvim",
	"https://github.com/willothy/nvim-cokeline",
	"https://github.com/sphamba/smear-cursor.nvim",
	"https://github.com/rcarriga/nvim-notify",
	"https://github.com/nvim-mini/mini.starter",

	-- code
	"https://github.com/neovim/nvim-lspconfig",
	"https://github.com/windwp/nvim-autopairs",
	"https://github.com/stevearc/conform.nvim",
	"https://github.com/mfussenegger/nvim-lint",
	"https://github.com/hrsh7th/nvim-cmp",
	"https://github.com/mason-org/mason.nvim",
	"https://github.com/rachartier/tiny-inline-diagnostic.nvim",
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "main" },
	"https://github.com/MeanderingProgrammer/render-markdown.nvim",

	-- utils
	"https://github.com/nvim-telescope/telescope.nvim",
	{ src = "https://github.com/nvim-telescope/telescope-fzf-native.nvim", build = "make" },
	"https://github.com/nvim-tree/nvim-tree.lua",
	"https://github.com/selimacerbas/live-server.nvim",
	"https://github.com/3rd/image.nvim",
}, { load = true })
