#Key bindings
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
bind-key r source-file ~/.config/tmux/tmux.conf
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

#Key bindings
# bind-key + T for theme settings

#Tmux options
set-option -g mouse on
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g pane-base-index 1
set-option -g status-position top
set -as terminal-features "*:hyperlinks"
set -gq allow-passthrough on
set -g visual-activity off

#Tmux plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'

#Tmux-kanagawa/dragon config
set -g @ukiyo-theme "kanagawa/dragon"
set -g @ukiyo-plugins "network-bandwidth"
set -g @ukiyo-border-contrast true

set -g pane-border-lines "heavy"
set -g pane-border-style "fg=#ff9e64,bg=default"
set -g pane-active-border-style "fg=#ff9e64,bg=default"

run '~/.config/tmux/plugins/tpm/tpm'

set -g window-style 'bg=default'
set -g window-active-style 'bg=default'
